version: "3.9"

services:

  app:
    container_name: fastapi-app
    restart: always
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    environment:
      DB_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - 8000:8000
    depends_on:
      - db

    volumes:
      - .:/app
  db:

    # This isn't the official PostgreSQL image; it's a pre-built version that
    # already includes the pgvector extension, which is used for storing and
    # searching vector embeddings (essential for AI/RAG applications).
    image: ankane/pgvector

    container_name: postgres-db

    restart: always

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d



volumes:
  postgres-data: