"""migration

Revision ID: 6eb688b49412
Revises: 
Create Date: 2025-07-16 15:59:04.868024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '6eb688b49412'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('scraping_status', sa.Enum('PENDING', 'SCRAPING', 'COMPLETED', name='scrapingstatus'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_websites_id'), 'websites', ['id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hashed_key', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_key'),
    sa.UniqueConstraint('prefix')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_website_id'), 'chat_sessions', ['website_id'], unique=False)
    op.create_table('scraped_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_content_id'), 'scraped_content', ['id'], unique=False)
    op.create_index(op.f('ix_scraped_content_website_id'), 'scraped_content', ['website_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_session_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.Enum('USER', 'BOT', name='messagesender'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_chat_session_id'), 'messages', ['chat_session_id'], unique=False)
    op.create_index('messages_time_created_desc', 'messages', ['chat_session_id', sa.literal_column('time_created DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('messages_time_created_desc', table_name='messages')
    op.drop_index(op.f('ix_messages_chat_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_scraped_content_website_id'), table_name='scraped_content')
    op.drop_index(op.f('ix_scraped_content_id'), table_name='scraped_content')
    op.drop_table('scraped_content')
    op.drop_index(op.f('ix_chat_sessions_website_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_websites_id'), table_name='websites')
    op.drop_table('websites')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
